### ISSUE TITLE
There seems to be repeated retracted (dead link) releases, which is tiresome noise.

### ISSUE THREAD

**Issue by rwperrott** [AZ-X/pique#12]
Maybe you need to have a unit test which validates your code, before you do a release, to reduce this annoying (aborted) release noise.

**Comment by AZ-X** [comment]
Hello watcher, do you think a unit test could solve unknown fantasy from code?
Check it:
https://github.com/AZ-X/action-automatic-releases
This is where noise coming from. Of course releasing JS is much harder than JAVA, do you agree?

**Comment by AZ-X** [comment]
I keep this issue for you. Leave it open if you don't understand anything about code.

**Comment by rwperrott** [comment]
I thought that this maybe a better alternative to the dnscrypt-proxy service, given the self-positive comparisons with dnscrypt-proxy, but it looks like premature speculation now, given no usable product to prove it, and the unhelpful response leads me to close the issue and give up on watching for a usable product.

**Comment by AZ-X** [comment]
Do you think it is a product? How wonderful? Should you donate or pay for the products?
>  I don't care.
