### ISSUE TITLE
Can this replace for NextDNS Windows Client?

### ISSUE THREAD

**Issue by 3xploiton3** [AZ-X/pique#25]
my machine windows 10 v1809,
i currently use nextdns service, 

can you provide more tutorial, how to use this for windows sir? 
(easy setup like nextdns client)

**Comment by AZ-X** [comment]
@3xploiton3 I am NOT going to replace NextDNS. However you can try this then create a wiki page for us to show how to replace other DNS client and whether it works or not.

**Comment by AZ-X** [comment]
A fake easy setup is a worse thing for DNS in my opinion.
